"""added new badges

Revision ID: 393fc81c184e
Revises: 0baf18b6fc98
Create Date: 2025-04-16 14:55:40.125212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393fc81c184e'
down_revision = '0baf18b6fc98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('criteria_type', sa.String(length=50), nullable=False),
    sa.Column('criteria_value', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('xp_value', sa.Integer(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('badge_id')
    )
    op.create_table('user_badges',
    sa.Column('user_badge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.badge_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_badge_id')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('enrollment_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('enrollment_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    op.drop_table('user_badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
