"""notification shown

Revision ID: 49320448098f
Revises: 7dc68c1a71a9
Create Date: 2025-05-24 13:26:34.964634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49320448098f'
down_revision = '7dc68c1a71a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_shown', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_column('notification_shown')

    # ### end Alembic commands ###
