"""added is confiremed

Revision ID: 50a65854dbb8
Revises: 393fc81c184e
Create Date: 2025-04-28 14:54:05.614602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a65854dbb8'
down_revision = '393fc81c184e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user_badges')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_confirmed')

    op.create_table('_alembic_tmp_user_badges',
    sa.Column('user_badge_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('badge_id', sa.INTEGER(), nullable=False),
    sa.Column('earned_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.badge_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_badge_id'),
    sa.UniqueConstraint('badge_id', name='uq_user_badges_badge_id')
    )
    # ### end Alembic commands ###
