"""removed lesson order

Revision ID: 922e75091436
Revises: 4e29079c181d
Create Date: 2025-03-27 17:48:27.542606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922e75091436'
down_revision = '4e29079c181d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('lesson_order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_order', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
