"""duration to lessons

Revision ID: 987480aa8584
Revises: ee1f467dcbc6
Create Date: 2025-04-04 21:38:14.934587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987480aa8584'
down_revision = 'ee1f467dcbc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
