"""added two new models, corrected the course table name

Revision ID: f24c73df8bb8
Revises: 8dcabe1a2a8b
Create Date: 2025-03-15 22:55:56.087446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24c73df8bb8'
down_revision = '8dcabe1a2a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('course_image_url', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_table('lessons',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('lesson_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.drop_table('course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('instructor_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('category', sa.VARCHAR(length=80), nullable=False),
    sa.Column('creation_date', sa.DATETIME(), nullable=False),
    sa.Column('last_update', sa.DATETIME(), nullable=False),
    sa.Column('course_image_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.drop_table('lessons')
    op.drop_table('enrollments')
    op.drop_table('courses')
    # ### end Alembic commands ###
